name: Auto Assign Issues to Projects

on:
  issues:
    types: [opened]
env:
  MY_GITHUB_TOKEN: ${{ secrets.ADD_ISSUE_TO_BEHOVSPROSJEKT_TOKEN }}

jobs:
  assign_to_project:
    runs-on: ubuntu-latest
    name: Assign issue to project
    steps:
      - name: Assign new issues to GitHub Project
        uses: srggrs/assign-one-project-github-action@1.2.1
        with:
          project: "https://github.com/orgs/Informasjonsforvaltning/projects/3"
          column_name: "Avklare behov"
